// Generated by gencpp from file phantom_omni/OmniFeedback.msg
// DO NOT EDIT!


#ifndef PHANTOM_OMNI_MESSAGE_OMNIFEEDBACK_H
#define PHANTOM_OMNI_MESSAGE_OMNIFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace phantom_omni
{
template <class ContainerAllocator>
struct OmniFeedback_
{
  typedef OmniFeedback_<ContainerAllocator> Type;

  OmniFeedback_()
    : force()
    , position()
    , torque()
    , thetas()  {
    }
  OmniFeedback_(const ContainerAllocator& _alloc)
    : force(_alloc)
    , position(_alloc)
    , torque(_alloc)
    , thetas(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _force_type;
  _force_type force;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _torque_type;
  _torque_type torque;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _thetas_type;
  _thetas_type thetas;





  typedef boost::shared_ptr< ::phantom_omni::OmniFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::phantom_omni::OmniFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct OmniFeedback_

typedef ::phantom_omni::OmniFeedback_<std::allocator<void> > OmniFeedback;

typedef boost::shared_ptr< ::phantom_omni::OmniFeedback > OmniFeedbackPtr;
typedef boost::shared_ptr< ::phantom_omni::OmniFeedback const> OmniFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::phantom_omni::OmniFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::phantom_omni::OmniFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace phantom_omni

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'phantom_omni': ['/home/kid/catkin_ws/src/phantom_omni_/phantom_omni_/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::phantom_omni::OmniFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::phantom_omni::OmniFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::phantom_omni::OmniFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::phantom_omni::OmniFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::phantom_omni::OmniFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::phantom_omni::OmniFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::phantom_omni::OmniFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4fff792fe66e9b3da7728a73d600f71b";
  }

  static const char* value(const ::phantom_omni::OmniFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4fff792fe66e9b3dULL;
  static const uint64_t static_value2 = 0xa7728a73d600f71bULL;
};

template<class ContainerAllocator>
struct DataType< ::phantom_omni::OmniFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "phantom_omni/OmniFeedback";
  }

  static const char* value(const ::phantom_omni::OmniFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::phantom_omni::OmniFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This is the force as estimated from the applied torques as well as the current\n\
# end effector position of the robot arm                           \n\
geometry_msgs/Vector3  force                                                                  \n\
geometry_msgs/Vector3  position  \n\
geometry_msgs/Vector3  torque\n\
geometry_msgs/Vector3  thetas\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::phantom_omni::OmniFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::phantom_omni::OmniFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.force);
      stream.next(m.position);
      stream.next(m.torque);
      stream.next(m.thetas);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OmniFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::phantom_omni::OmniFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::phantom_omni::OmniFeedback_<ContainerAllocator>& v)
  {
    s << indent << "force: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.force);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "torque: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.torque);
    s << indent << "thetas: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.thetas);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PHANTOM_OMNI_MESSAGE_OMNIFEEDBACK_H
